language: java
dist: trusty
sudo: false
addons:
  sonarqube:
    organization: "kizombadev-github" 
    token:
      secure: $SONAR_TOKEN 
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
