language: java
dist: trusty
install: true
sudo: false
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - $HOME/jvm
    - $HOME/maven
notifications:
  email: false
before_script:
 - chmod +x ./travis.sh
script: ./travis.sh
