language: java
dist: trusty
sudo: false
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - $HOME/jvm
    - $HOME/maven
addons:
  sonarqube:
    organization: "kizombadev-github" 
    token:
      secure: $SONAR_TOKEN 
notifications:
  email: false
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
